# 개념 정리

## 1. 머신 러닝과 딥러닝

### 1.1. 인공지능, 머신 러닝과 딥러닝

인공지능 > 머신 러닝 > 딥러닝 순의 관계.  
머신 러닝: 주어진 데이터를 인간이 먼저 처리함.  
딥러닝: 데이터를 신경망에 적용하면 컴퓨터가 스스로 분석한 후 답을 찾음.


### 1.2. 머신 러닝이란

#### 1.2.1. 머신 러닝 학습 과정
- 크게 학습 단계와 예측 단계로 구분.
- 주요 구성 요소: 데이터와 모델(모형).
- 모델의 학습 절차: 모델 선택 > 모델 학습 및 평가 > 평가를 바탕으로 모델 업데이트

#### 1.2.2. 머신 러닝 학습 알고리즘
- 지도 학습: 정답을 알려주고 학습시키는 방법. 분류, 회귀.
- 비지도 학습: 정답을 알려주지 않고 특징이 비슷한 데이터를 클러스터링하여 예측하는 학습 방법. 군집, 차원 축소.
- 강화 학습: 분류할 데이터도 없고 정답도 없음. 자신의 행동에 대한 보상을 받으며 학습을 진행함. 게임이 대표적 사례.

### 1.3. 딥러닝이란

딥러닝: 인간의 신경망 원리를 모방한 심층 신경망 이론을 기반으로 고안된 머신 러닝 방법의 일종.

#### 1.3.1. 딥러닝 학습 과정
- 데이터 준비
- 모델(모형) 정의: 신경망 생성. 은닉층 개수가 많을수록 성능이 좋아지지만 과적합 발생 확률이 높음.
- 모델(모형) 컴파일: 활성화 함수, 손실 함수, 옵티마이저 선택. 데이터가 연속형이면 MSE, 이진 분류면 cross entropy 선택. 과적합을 피할 수 있는 활성화 함수 및 옵티마이저 선택이 중요.
- 모델(모형) 훈련: 한 번에 처리할 데이터양 지정. 일정 한 묶음으로 나누어 처리할 수 있는 배치와 훈련의 횟수인 에포크 선택이 중요. 값의 변화를 확인하며 파라미터와 하이퍼파라미터 최적 값을 찾아야 함.
- 모델(모형) 예측: 실제로 예측을 진행해보는 단계.
- 핵심 구성 요소: 신경망과 역전파. 

#### 1.3.2. 딥러닝 학습 알고리즘
지도 학습
- 합성곱 신경망(Convolutional Neural Network, CNN): 이미지 분류, 이미지 인식, 이미지 분할
- 순환 신경망(Recurrent Neural Network, RNN): 시계열 데이터 분류. 역전파 과정에서 기울기 소멸 문제가 발생하는 단점을 개선하기 위해 LSTM(Long Short-Term Memory)로 망각 게이트, 입력 게이트, 출력 게이트를 도입.  

비지도 학습
- 워드 임베딩: 자연어 처리 분야로, 단어를 벡터로 표현. Word2Vec와 GloVe 많이 사용.
- 군집: 머신 러닝의 군집과 다르지 않으나 딥러닝과 함께 사용하면 모델 성능을 높일 수 있어 신경망에서 군집 알고리즘 사용 등으로 활용.

전이 학습: 사전 학습 모델을 가지고 원하는 학습에 미세 조정 기법을 이용해 학습시키는 방법.  
사전 학습 모델: 풀고자 하는 문제와 비슷하면서 많은 데이터로 이미 학습이 되어 있는 모델. VGG, 인셉션, MobileNet 등의 모델을 사용해 효율적인 학습 진행.

강화 학습: 머신 러닝과 동일.

## 2. 실습 환경 설정과 파이토치 기초

### 2.1. 파이토치 개요

#### 2.1.1. 파이토치 특징 및 장점
특징: GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임 워크
- GPU : 연산 속도를 빠르게 하는 역할. 미분을 써서 기울기를 계산할 때 GPU가 빠름. 병렬 연산에서 CPU 속도보다 GPU 속도가 훨씬 빠름.
- 텐서: 파이토치의 데이터 형태. 단일 데이터 형식으로 된 자료들의 다차원 행렬. 간단한 명령어를 사용해 GPU로 연산을 수행하게 할 수 있음.
- 동적 신경망: 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망. 학습 중에 은닉층을 추가하거나 제거. 연산 그래프를 정의하는 것과 동시에 값도 초기화되는 Define by Run 방식 사용.

장점
- 단순함(효율적인 계산): 파이썬 환경과 쉽게 통합 가능. 디버깅이 직관적이고 간결.
- 성능(낮은 CPU 활용): 텐서플로와 비교해 CPU 사용률이 낮음. 학습 및 추론 속도가 빠르고 다루기 쉬움.
- 직관적인 인터페이스: 텐서플로처럼 잦은 API 변경이 없어 진입 장벽이 낮음.

#### 2.1.2. 파이토치의 아키텍처

크게 세 개의 계층으로 나눔. 상위부터 파이토치 API, 파이토치 엔진, 텐서에 대한 연산 처리.

파이토치 API: 사용자가 이해하기 쉬운 API를 제공하여 텐서에 대한 처리와 신경망을 구축하고 훈련할 수 있도록 도움. 사용자 인터페이스를 제공하지만 실제 계산은 수행하지 않고, C++로 작성된 파이토치 엔진으로 작업을 전달하는 역할.
- torch: GPU를 지원하는 텐서 패키지
- torch.autograd: 자동 미분 패키지
- torch.nn: 신경망 구축 및 훈련 패키지
- torch.multiprocessing: 파이썬 멀티프로세싱 패키지
- torch.utils: DataLoader 및 기타 유틸리티를 제공하는 패키지

파이토치 엔진: 다차원 텐서 및 자동 미분 처리.
- Autograd C++: 가중치, 바이어스를 업데이트하는 과정에서 필요한 미분을 자동으로 계산
- Aten C++: C++ 텐서 라이브러리 제공
- JIT C++: 계산을 최적화하기 위한 JIT 컴파일러
- Python API: C++로 감싼 것들을 파이썬 형태로 제공

연산 처리: 가장 아래 계층에 속하는 C 또는 CUDA 패키지. 상위의 API에서 할당된 거의 모든 계산을 수행. CPU와 GPU(TH, THC)를 이용해 효율적인 데이터 구조, 다차원 텐서에 대한 연산을 처리.

텐서를 메모리에 저장하기
- 텐서는 1차원 배열 형태여야만 메모리에 저장할 수 있음. 변환된 1차원 배열을 스토리지라고 함.
- 오프셋: 텐서에서 첫 번째 요소가 스토리지에 저장된 인덱스
- 스트라이드: 각 차원에 따라 다음 요소를 얻기 위해 건너뛰기가 필요한 스토리지의 요소 개수. 메모리에서의 텐서 레이아웃을 표현.

### 2.2. 파이토치 기초 문법

#### 2.2.1. 텐서 다루기

- 배열처럼 인덱스를 바로 지정하거나 슬라이스 등을 사용할 수 있음.  
- 자료형: torch.FloatTensor(32비트 부동 소수점), torch.DoubleTensor(64비트 부동 소수점), torch.LongTensor(64비트 부호가 있는 정수)  
- 다양한 수학 연산 가능, 타입이 같아야 함.
- 차원 변경: 대표적으로 view 이용. 넘파이의 reshape과 유사. stack, cat으로 텐서 결합. t, transpose는 차원을 교환. transpose는 차원의 순서를 변경할 때도 사용.

#### 2.2.2. 데이터 준비
- 데이터가 이미지일 경우 분산된 파일에서 데이터를 읽은 후 전처리를 하고 배치 단위로 분할하여 처리
- 데이터가 텍스트일 경우 임베딩 괒어을 거쳐 서로 다른 길이의 시퀀스를 배치 단위로 분할하여 처리
- 데이터가 복잡하지 않은 형태일 때는 판다스 라이브러리를 이용해 파일을 불러옴
- 커스텀 데이터셋: 대량의 데이터를 한 번에 다 부르지 않고 조금씩 나누어 불러서 사용하는 방식
- 데이터로더(DataLoader): 학습에 사용될 데이터 전체를 보관했다가 모델 학습을 할 때 배치 크기만큼 데이터를 꺼내서 사용. 내부적으로 반복자(iterator)에 포함된 인덱스를 이용해 배치 크기만큼 데이터를 반환.
- 토치비전(torchvision): 파이토치에서 제공하는 데이터셋 모음 패키지.

#### 2.2.3. 모델 정의
- 계층(layer): 모듈 또는 모듈을 구성하는 한 개의 계층. 합성곱층(convolutional layer), 선형계층(linear layer) 등
- 모듈(module): 한 개 이상의 계층이 모여서 구성된 것. 모듈이 모여 새로운 모듈을 만들 수 있음.
- 모델(model): 최종적으로 원하는 네트워크. 한 개의 모듈이 모델이 될 수도 있음.

- 단순 신경망을 정의하는 방법: nn.Module을 상속받지 않는 매우 단순한 모델. 구현이 쉽고 단순함.
- nn.Module()을 상속하여 정의하는 방법: __init__()에서 모델에서 사용될 모듈(nn.Linear, nn.Conv2d), 활성화 함수 등을 정의. forward()에서 모델에서 실행되어야 하는 연산을 정의.
- Sequential 신경망을 정의하는 방법: __init__()에서 사용할 네트워크 모델들을 정의해주고, forward() 함수에서 모델에서 실행되어야 할 계산을 가독성이 뛰어나게 코드로 작성할 수 있음. 모델의 계층이 복잡할수록 효과가 뛰어남.
- 함수로 신경망을 정의하는 방법: Sequential 이용과 동일하지만, 변수에 저장해 놓은 계층들을 재사용할 수 있는 장점이 있음. 모델이 복잡해지는 단점이 있음.
- model.modules(): 모델의 네트워크에 대한 모든 노드 반환
- model.children(): 같은 수준의 하위 노드 반환

#### 2.2.4. 모델의 파라미터 정의
- 손실 함수(loss function): 학습하는 동안 출력과 실제 값(정답) 사이의 오차 측정. 이진 분류에서 BCELoss, 다중 클래스 분류에서 CrossEntropyLoss, 회귀에서 MSELoss를 주로 사용.
- 옵티마이저(optimizer): 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법 결정. step() 메서드를 통해 전달받은 파라미터를 업데이트하고 모델의 파라미터 별로 다른 기준 적용.
- 학습률 스케줄러(learning rate scheduler): 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소시켜줌. 학습 초기에 빠르게 진행하다가 전역 최소점 근처에 다다르면 학습률을 줄여 최적점을 찾아갈 수 있도록 해줌.
- 지표(metrics): 훈련과 테스트 단계 모니터링

#### 2.2.5. 모델 훈련
- optimizer.zero_grad() 메서드를 이용해 기울기 초기화. 파이토치는 loss.backward() 메서드로 기울기 값을 계산하는데, 이전 기울기 값에 누적하여 계산되므로 초기화가 필요함.

#### 2.2.6. 모델 평가
- 함수와 모듈을 이용하는 두 가지 방법이 있음. 사이킷런의 혼동 행렬도 이용 가능.

#### 2.2.7. 훈련 과정 모니터링
- 텐서보드로 학습에 사용되는 파라미터 값의 변화를 시각화해서 살펴보고 성능을 추적하거나 평가하는 용도로 사용할 수 있음.
- 텐서보드 사용방법: 텐서보드 설정 > 텐서보드에 기록 > 모델 구조 살펴보기

- model.train(): 훈련 데이터셋에 사용. 모델 훈련이 진행될 것을 알림. 드롭아웃(dropout) 활성화.
- model.eval(): 모델을 평가할 때는 모든 노드를 사용하겠다는 의미로 검증과 테스트 데이터셋에 사용.

# 코드 필사

## 2. 실습 환경 설정과 파이토치 기초

### 2.2. 파이토치 기초 문법

#### 2.2.1. 텐서 다루기

In [1]:
import torch
print(torch.tensor([[1, 2], [3, 4]])) # 2차원 형태의 텐서 생성
print(torch.tensor([[1, 2], [3, 4]], device="cuda:0")) # GPU에 텐서 생성
print(torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)) # dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
temp = torch.tensor([[1, 2], [3, 4]])
print(temp.numpy()) # 텐서를 ndarray로 변환

temp = torch.tensor([[1, 2], [3, 4]], device="cuda:0")
print(temp.to("cpu").numpy()) # GPU상의 텐서를 CPU의 텐서로 변환한 후 ndarray로 변환

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [4]:
temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7]) # 파이토치로 1차원 벡터 생성
print(temp[0], temp[1], temp[-1]) # 인덱스로 접근
print('---------------------')
print(temp[2:5], temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
---------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [5]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w - v)

tensor([2, 2, 3])


In [7]:
temp = torch.tensor([[1, 2], [3, 4]]) # 2x2 행렬 생성

print(temp.shape)
print('--------------------------')
print(temp.view(4, 1)) # 2x2 행렬을 4x1로 변형
print('--------------------------')
print(temp.view(-1)) # 2x2 행렬을 1차원 벡터로 변형
print('--------------------------')
print(temp.view(1, -1)) # 원소 개수를 유지한 채 (1, ?)의 형태로 변형 > (1, 4)
print('--------------------------')
print(temp.view(-1, 1)) # (?, 1) > (4, 1)

torch.Size([2, 2])
--------------------------
tensor([[1],
        [2],
        [3],
        [4]])
--------------------------
tensor([1, 2, 3, 4])
--------------------------
tensor([[1, 2, 3, 4]])
--------------------------
tensor([[1],
        [2],
        [3],
        [4]])


#### 2.2.2. 데이터 준비

In [8]:
# 단순하게 파일을 불러와서 사용

# import pandas as pd
# import torch
# data = pd.read_csv('../class2.csv')

# x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
# CSV 파일의 x 칼럼의 값을 넘파이 배열로 받아 Tensor(dtype)으로 바꿈
# y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

In [9]:
# # 커스텀 데이터셋을 만들어서 사용

# class CustomDataset(torch.utils.data.Dataset):
#     def __init__(self): # 필요한 변수를 선언하고, 데이터셋의 전처리를 해주는 함수
#     def __len__(self): # 데이터셋의 길이, 즉 총 샘플의 수를 가져오는 함수
#     def __getitem__(self, index): # 데이터셋에서 특정 데이터를 가져오는 함수

In [10]:
# # 예제

# import pandas as pd
# import torch
# from torch.utils.data import Dataset
# from torch.utils.data import DataLoader

# class CustomDataset(Dataset):
#     def __init__(self, csv_file): # csv_file 파라미터를 통해 데이터셋을 불러옴
#         self.label = pd.read_csv(csv_file)

#     def __len__(self): # 전체 데이터셋의 크기 반환
#         return len(self.label)

#     def __getitem__(self, idx): # 전체 x와 y 데이터 중에 해당 idx번째 데이터를 가져옴
#         sample = torch.tensor(self.label.iloc[idx, 0:3]).int()
#         label = torch.tensor(self.label.iloc[idx, 3]).int()
#         return sample, label

# tensor_dataset = CustomDataset('../covtype.csv') # 데이터셋으로 covtype.csv 사용
# dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True)
# # 데이터셋을 torch.utils.data.DataLoader에 파라미터로 전달

In [12]:
# # 파이토치에서 제공하는 데이터셋 사용

# import torchvision.transforms as transforms

# mnist_transform = transforms.Compose([
#     transforms.ToTensor(),
#     transforms.Normalize((0.5,), (1.0,))
# ]) # 평균이 0.5, 표준편차가 1.0이 되도록 데이터의 분포를 조정

# from torchvision.datasets import MNIST
# import requests
# download_root = '../chap02/data/MNIST_DATASET' # 내려받을 경로 지정

# train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)
# valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)
# test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)

#### 2.2.3. 모델 정의

In [13]:
# # 단순 신경망을 정의하는 방법
# model = nn.Linear(in_features=1, out_features=1, bias=True)

In [14]:
# # nn.Module()을 상속하여 정의하는 방법

# class MLP(Module):
#     def __init__(self, inputs):
#         super(MLP, self).__init__()
#         self.layer = Linear(inputs, 1)  # 계층 정의
#         self.activation = Sigmoid() # 활성화 함수 정의

#     def forward(self, X):
#         X = self.layer(X)
#         X = self.activation(X)
#         return X

In [16]:
# Sequential 신경망을 정의하는 방법

import torch.nn as nn
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )

        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )

        self.layer3 = nn.Sequential(
            nn.Linear(in_features=30*5*5, out_features=10, bias=True),
            nn.ReLU(inplace=True)
        )


    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = x.view(x.shape[0], -1)
        x = self.layer3(x)
        return x

model = MLP() # 모델에 대한 객체 생성

print("Printing children\n------------------------------------")
print(list(model.children()))
print("\n\nPrinting Modules\n---------------------------------------")
print(list(model.modules()))

Printing children
------------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
---------------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(

In [17]:
# 함수로 신경망을 정의하는 방법

def MLP(in_features=1, hidden_features=20, out_features=1):
    hidden = nn.Linear(in_features=in_features, out_features=hidden_features, bias=True)
    activation = nn.ReLU()
    output = nn.Linear(in_features=hidden_features, out_features=out_features, bias=True)
    net = nn.Sequential(hidden, activation, output)
    return net

#### 2.2.4. 모델의 파라미터 정의

In [18]:
# from torch.optim import optimizer
# criterion = torch.nn.MSELoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
# scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer, lr_lambda=lambda epoch: 0.95 ** epoch)
# for epoch in range(1, 100+1): # 에포크 수만큼 데이터를 반복하여 처리
#     for x, y in dataloader: # 배치 크기만큼 데이터를 가져와서 학습 진행
#         optimizer.zero_grad()
# loss_fn(model(x), y).backward()
# optimizer.step()
# scheduler.step()

#### 2.2.5. 모델 훈련

In [20]:
# for epoch in range(100):
#     yhat = model(x_train)
#     loss = criterion(yhat, y_train)
#     optimizer.zero_grad() # 오차가 중첩적으로 쌓이지 않도록 초기화
#     loss.backward()
#     optimizer.step()

#### 2.2.6. 모델 평가

In [31]:
# pip install torchmetrics

In [24]:
# 함수를 이용해 모델을 평가

import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds, target, task='multiclass', num_classes=5)

In [25]:
# 모듈을 이용해 모델을 평가

import torch
import torchmetrics
metric = torchmetrics.Accuracy(task='multiclass', num_classes=5) # 모델 평가(정확도) 초기화

n_batches = 10
for i in range(n_batches):
    preds = torch.randn(10, 5).softmax(dim=-1)
    target = torch.randint(5, (10,))

    acc = metric(preds, target)
    print(f"Accuracy on batch {i}: {acc}") # 현재 배치에서 모델 평가(정확도)

acc = metric.compute()
print(f"Accuracy on all data: {acc}") # 모든 배치에서 모델 평가(정확도)

Accuracy on batch 0: 0.20000000298023224
Accuracy on batch 1: 0.20000000298023224
Accuracy on batch 2: 0.30000001192092896
Accuracy on batch 3: 0.10000000149011612
Accuracy on batch 4: 0.20000000298023224
Accuracy on batch 5: 0.0
Accuracy on batch 6: 0.4000000059604645
Accuracy on batch 7: 0.4000000059604645
Accuracy on batch 8: 0.20000000298023224
Accuracy on batch 9: 0.10000000149011612
Accuracy on all data: 0.20999999344348907


#### 2.2.7. 훈련 과정 모니터링

In [32]:
# pip install tensorboard

In [28]:
# import torch
# from torch.utils.tensorboard import SummaryWriter
# writer = SummaryWriter("../chap02/tensorboard") # 모니터링에 필요한 값들이 저장될 위치

# for epoch in range(num_epochs):
#     model.train() # 학습 모드로 전환(dropout=True)
#     batch_loss = 0.0

#     for i, (x, y) in enumerate(dataloader):
#         x, y = x.to(device).float(), y.to(device).float()
#         outputs = model(x)
#         loss = criterion(outputs, y)
#         writer.add_scalar("Loss", loss, epoch) # 스칼라 값(오차)을 기록
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()

# writer.close() # SummaryWriter가 더 이상 필요하지 않으면 close() 메서드 호출

In [29]:
# tensorboard --logdir=../chap02/tensorboard --port=6006

In [30]:
# model.eval() # 검증 모드로 전환(dropout=False)
# with torch.no_grad():
#     valid_loss = 0

#     for x, y in valid_dataloader:
#         outputs = model(x)
#         loss = F.cross_entropy(outputs, y.long(), squeeze())
#         valid_loss += float(loss)
#         y_hat += [outputs]

# valid_loss = valid_loss / len(valid_loader)