<a href="https://colab.research.google.com/github/burningdust/ESAA/blob/main/OB_assignment/ESAA_OB_study01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 개념 정리

## 8. 텍스트 분석

### 8-1. 텍스트 분석 이해

텍스트 분석: 비정형 데이터인 텍스트 분석. 텍스트를 word 기반의 피처로 추출하고 빈도수와 같은 숫자 값을 부여해 단어의 조합 벡터값으로 변환하는 것을 피처 벡터화 또는 피처 추출이라고 함. 대표적으로 BOW(Bag of Words)와 Word2Vec 방법이 있음.  
  
텍스트 분석 수행 프로세스
1. 텍스트 전처리: 피처로 만들기 전 클렌징, 대/소문자 변경, 토큰화 작업 등 텍스트 정규화 작업 수행
2. 피처 벡터화/추출: 피처 추출 후 벡터 값 할당
3. ML모델 수립 및 학습/예측/평가

### 8-2. 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화

클렌징: 불필요한 문자, 기호 등을 사전에 제거

텍스트 토큰화: 문서에서 문장을 분리하는 문장 토큰화와 문장에서 단어를 토큰으로 분리하는 단어
* 문장 토큰화: 문장의 마침표, 개행문자 등의 기호에 따라 분리하는 것이 일반적. NTLK의 sent_tokenize를 이용해 수행
* 단어 토큰화: 공백, 콤마, 마침표, 개행문자 등으로 분리. BOW와 같이 단어의 순서가 중요하지 않은 경우 문장 토큰화를 사용하지 않고 단어 토큰화만 해도 충분. NTLK의 word_tokenize를 이용해 수행. 문맥적인 의미가 무시되는 단점이 있으며, 이를 해결하기 위해 n-gram을 이용해 연속된 단어를 n개 크기 윈도우로 토큰화함.

스톱 워드 제거: 영어의 is, the 등 분석에 큰 의미가 없는 문법 요소를 스톱 워드라 하며 빈번함으로 중요한 단어로 인지될 수 있으므로 제거.

Stemming과 Lemmatization: 문법적 또는 의미적으로 변화하는 단어의 원형을 찾는 것. Lemmatization이 Stemming보다 정교하며 의미론적인 기반에서 단어의 원형을 찾지만 시간이 더 오래 걸림. NLTK에서 제공하는 Stemmer는 Porter, Lancaster, Snowball Stemmer가 있고 Lemmatization을 위해서는 WordNetLemmatizer를 제공함.

### 8-3. Bag of Words - BOW

Bag of Words : 모든 단어를 문맥이나 순서를 무시하고 일괄적으로 단어에 대해 빈도 값을 부여해 피처 값을 추출하는 모델. 쉽고 빠른 구축의 장점으로 여러 분야에서 활용도가 높음. 문맥 의미 반영이 부족하고 피처 벡터화로 만든 데이터 세트가 희소 행렬 형태가 되기 쉽다는 단점이 있음.

피처 벡터화: 텍스트 데이터를 머신러닝 알고리즘에 적용하기 위해 벡터 값으로 변환하는 작업. BOW 모델에서는 모든 단어를 칼럼 형태로 나열한 후 해당 단어의 횟수나 정규화된 빈도를 값으로 부여하는 데이터 세트 모델로 변경.
- 카운트 벡터화: 단어 피처 값을 단어가 나타난 횟수로 부여. 사이킷런의 CountVectorizer로 구현.
- TF-IDF 벡터화: 개별 문서에서 자주 나타나는 문서에 높은 가중치를 주되, 모든 문서에서 전반적으로 자주 나타나는 단어는 페널티 부과. 사이킷런의 TfidVectorizer로 구현.

CountVectorizer를 이용한 텍스트 피처 벡터화 방법
1. 사전 데이터 가공: 영어의 경우 모든 문자를 소문자로 변경하는 등 전처리 작업
2. 토큰화: 디폴트로 단어 기준으로 n_gram_range를 반영해 단어 토큰화
3. 텍스트 정규화: Stop Words 필터링만 수행, Stemmer와 Lemmatize는 지원되지 않아 따로 수행 필요
4. 피처 벡터화: 파라미터를 이용해 토큰화된 단어를 피처로 추출 후 단어 빈도수 벡터 값 적용

희소 행렬: 대규모 행렬의 대부분의 값을 0이 차지하는 행렬. BOW 형태를 가진 언어 모델의 피처 벡터화는 대부분 희소 행렬. 불필요하게 메모리 공간이 많이 필요하므로 COO 형식과 CSR 형식 등으로 변환.
- COO(Coordinate) 형식: 0이 아닌 데이터만 별도의 데이터 배열에 저장하고, 그 행/열의 위치를 별도의 배열로 저장하는 방식. Scipy의 sparse 패키지로 구현.
- CSR(Compressed Sparse Row) 형식: COO 형식 변환에서 행 위치 배열의 반복을 제거하기 위해 행 위치 배열을 다시 위치 배열로 변환.

# 코드 필사

### 8-2. 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화

In [ ]:
from nltk import sent_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
You can see it out your window or on your television. \
You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text=text_sample)
print(type(sentences),len(sentences))
print(sentences)

<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
from nltk import word_tokenize

setence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(setence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [ ]:
from nltk import word_tokenize, sent_tokenize

# 여러 개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화하게 만드는 함수 생성
def tokenize_text(text):

  # 문장별로 분리 토큰
  sentences = sent_tokenize(text)
  # 분리된 문장별 단어 토큰화
  word_tokens = [word_tokenize(sentence) for sentence in sentences]
  return word_tokens

# 여러 문장에 대해 문장별 단어 토큰화 수행.
word_tokens = tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
print('영어 stop words 개수:', len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 개수: 198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']


In [ ]:
import nltk

stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []
# 위 예제에서 3개의 문장별로 얻은 word_tokens list에 대해 스톱 워드를 제거하는 반복문
for sentence in word_tokens:
  filtered_words = []
  # 개별 문장별로 토큰화된 문장 list에 대해 스톱 워드를 제거하는 반복문
  for word in sentence:
    # 소문자로 모두 변환합니다.
    word = word.lower()
    # 토큰화된 개별 단어가 스톱 워드의 단어에 포함되지 않으면 word_tokens에 추가:
    if word not in stopwords:
      filtered_words.append(word)
  all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


In [2]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused'))
print(stemmer.stem('happier'), stemmer.stem('happiest'))
print(stemmer.stem('fancier'), stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [3]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing', 'v'), lemma.lemmatize('amuses', 'v'), lemma.lemmatize('amused', 'v'))
print(lemma.lemmatize('happier', 'a'), lemma.lemmatize('happiest', 'a'))
print(lemma.lemmatize('fancier', 'a'), lemma.lemmatize('fanciest', 'a'))

[nltk_data] Downloading package wordnet to /root/nltk_data...


amuse amuse amuse
happy happy
fancy fancy


### 8-3. Bag of Words - BOW

In [5]:
import numpy as np

dense = np.array([[3, 0, 1], [0, 2, 0]])

In [6]:
from scipy import sparse

# 0이 아닌 데이터 추출
data = np.array([3, 1, 2])

# 행 위치와 열 위치를 각각 배열로 생성
row_pos = np.array([0, 0, 1])
col_pos = np.array([0, 2, 1])

# sparse 패키지의 coo_matrix를 이용해 COO 형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos)))

In [7]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [8]:
from scipy import sparse

dense2 = np.array([[0, 0, 1, 0, 0, 5],
                   [1, 4, 0, 3, 2, 5],
                   [0, 6, 0, 3, 0, 0],
                   [2, 0, 0, 0, 0, 0],
                   [0, 0, 0, 7, 0, 8],
                   [1, 0, 0, 0, 0, 0]])

# 0이 아닌 데이터 추출
data2 = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

# 행 위치와 열 위치를 각각 array로 생성
row_pos = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

# COO 형식으로 변환
sparse_coo = sparse.coo_matrix((data2, (row_pos, col_pos)))

# 행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성
row_pos_ind = np.array([0, 2, 7, 9, 10, 12, 13])

# CSR 형식으로 변환
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [9]:
dense3 = np.array([[0, 0, 1, 0, 0, 5],
                   [1, 4, 0, 3, 2, 5],
                   [0, 6, 0, 3, 0, 0],
                   [2, 0, 0, 0, 0, 0],
                   [0, 0, 0, 7, 0, 8],
                   [1, 0, 0, 0, 0, 0]])

coo = sparse.coo_matrix(dense3)
csr = sparse.csr_matrix(dense3)