<a href="https://colab.research.google.com/github/burningdust/ESAA/blob/main/YB_assignment/ESAA_YB_exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [56]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [57]:
print('numpy version:', np.__version__)
np.show_config()

numpy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

#### 3. Create a null vector of size 10 (★☆☆)

In [58]:
arraynull = np.full(10, np.nan)
print(arraynull)

[nan nan nan nan nan nan nan nan nan nan]


#### 4. How to find the memory size of any array (★☆☆)

In [59]:
array4 = np.array([1, 2, 3, 4, 5])
print(array4.nbytes)

40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [60]:
array5 = np.full(10, np.nan)
array5[4] = 1
print(array5)

[nan nan nan nan  1. nan nan nan nan nan]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [61]:
array6 = np.arange(10, 50)
print(array6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [62]:
array7 = array6[::-1]
print(array7)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [63]:
array8 = np.arange(0, 9).reshape(3, 3)
print(array8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [64]:
array9 = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(array9))

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [65]:
array10 = np.identity(3)
print(array10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [66]:
array11 = np.random.random((3, 3, 3,))
print(array11)

[[[0.68707977 0.16923614 0.58633147]
  [0.35280089 0.91766572 0.49477062]
  [0.31001778 0.81258038 0.43822896]]

 [[0.91025281 0.84498979 0.36159745]
  [0.46011093 0.39672548 0.1984806 ]
  [0.63214499 0.08071642 0.15652002]]

 [[0.56271961 0.07219993 0.25556598]
  [0.75693707 0.95096473 0.03882096]
  [0.43023622 0.44589777 0.33539889]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [67]:
array12 = np.random.random((10, 10))
print('mininum value:', array12.min())
print('maximum value:', array12.max())

mininum value: 0.013529069812802219
maximum value: 0.9687012212574816


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [68]:
array13 = np.random.random(30)
print(array13.mean())

0.44831332243525684


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [69]:
array14 = np.ones((5, 5))
array14[1:-1, 1:-1] = 0
print(array14)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan  
False  
False  
nan  
True  
False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [70]:
array16 = np.diag(np.arange(1, 5), k = -1)
print(array16)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [71]:
array17 = np.zeros((8, 8))
array17[1::2, ::2] = 1
array17[::2, 1::2] = 1
print(array17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [72]:
array18 = np.unravel_index(100, (6, 7, 8))
print(array18)

(np.int64(1), np.int64(5), np.int64(4))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [73]:
array19 = np.random.random((5, 5))
array19 = (array19 - array19.mean()) / array19.std()
print(array19)

[[ 0.22534136  1.0342465  -1.45567924 -0.51954774 -1.21938873]
 [-0.96897376  1.40380895  0.58481182 -0.25346297 -0.22023906]
 [ 1.51293772  0.88119445 -0.73254449 -0.3838128  -0.01027631]
 [ 0.77787254  1.69488205 -0.85546588 -1.22304726  0.44474402]
 [-1.15285677  0.05923651 -1.45049102 -0.05662601  1.88333611]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [74]:
colortype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
array20 = np.array([(255, 0, 0, 255), (0, 0, 0, 0)], dtype = colortype)
print(array20)

[(255, 0, 0, 255) (  0, 0, 0,   0)]
